### ISSUE TITLE
Output given when no user match.

### ISSUE THREAD

**Issue by tusharnankani** [Poornartha/GitProfiles#1]
HI @Poornartha!

When there is no user matching/found, it notifies the user, but it still outputs an account. 
This can be avoided.
![0](https://user-images.githubusercontent.com/61280281/90444122-f8de8580-e0fa-11ea-8182-332b971b3da0.png)

Thank you
Tushar Nankani

**Comment by Poornartha** [comment]
Hi Tushar,
The output is absolutely correct.
Click on GitHub Button and check out the profile.
The Profile in fact has a username 'k'.
Easy way to know this: Check the URL of any profile.

 Thank You,
Poornartha Sawant

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tusharnankani** [comment]
My bad! I must have attached a wrong picture. 
What I meant is to show no output, when no valid username entered.

![Screenshot (236)](https://user-images.githubusercontent.com/61280281/90472197-9b1f5d00-e13d-11ea-92a9-97c5ab41b202.png)

There's no primary issue as such, but I just think it would be better if no output is given, right?
- also, I was just wondering, if `type-ahead` could be implemented! :)

**Comment by Poornartha** [comment]
Hi Tushar,
When the user is not found, it is not any random account.
I here am using a keydown event to handle state.
Thus, if the User is not found for Tushar, then the account fetched would
be the last one i.e. Tusha, which would be the closest one (Can be changed).
Plus, there would be a message that has a timeout, which you might have
noticed.
The issue with implementing type-ahead is the collection of the usernames
and as of now, I've not used any database of my own with this project.
Thus, possible, but, as of now, I've not thought about it. If you know an
easy way to implement that, do let me know.

Thank You,
Poornartha Sawant

**Comment by tusharnankani** [comment]
Hi @Poornartha 

> I here am using a keydown event to handle state.
Thus, if the User is not found for Tushar, then the account fetched would
be the last one i.e. Tusha, which would be the closest one (Can be changed).

Alright! Understood! Thanks 😇

> Plus, there would be a message that has a timeout, which you might have
noticed.

Yes, I did. It disappears after some time. 

> If you know an
easy way to implement that, do let me know.

I am trying to understand and learn more and more things, trying to get more and more exposure, so I would have your project in mind, when I try to implement type-ahead. 

Right now when I am analysing projects, I am just looking for enhancements, and improvements I can think of! 

Thanks for answering, the question! ^_^

**Comment by Poornartha** [comment]
Welcome, Tushar.

I have a lot to figure out, myself. Let me know if you need any help.
I don't have the best of projects, but I try my best.

Thank You,
Poornartha Sawant.

**Comment by tusharnankani** [comment]
Thanks @Poornartha! 🤗
